networks:
  hadoop:
      driver: bridge

services:
  hadoop-master:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      # Hadoop web UI and WebHDFS
      - 9870:9870
      # Hadoop job history server
      - 8088:8088
      - 7077:7077
      - 16010:16010
      - 4040:4040
    networks:
      - hadoop
    tty: true
    volumes:
      - ./data/scripts:/root/scripts
      - ./data/input/:/root/input
      - ./data/start-processing.sh:/root/start-processing.sh

  hadoop-worker1:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    networks:
      - hadoop
    ports:
      - 8040:8042
    tty: true

  hadoop-worker2:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    networks:
      - hadoop
    ports:
      - 8041:8042
    tty: true

  express-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    networks:
      - hadoop
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - hadoop-master
      - hadoop-worker1
      - hadoop-worker2